"""Extractor contracts and modality-specific adapters."""

from scope_modeler.extractors.base import (
    BaseExtractor,
    ExtractedObservation,
    ExtractorResult,
    ObservationValue,
)
from scope_modeler.extractors.audio import (
    AudioScopeExtractor,
    MockTranscriber,
    Transcriber,
    TranscriptionResult,
    TranscriptionSegment,
)
from scope_modeler.extractors.drawing import (
    DrawingGeometryModelClient,
    DrawingDimension,
    DrawingGeometrySummary,
    DrawingPoint,
    DrawingPrimitive,
    DrawingSemanticModelClient,
    DrawingSemanticInference,
    OpenAIDrawingGeometryClient,
    OpenAIDrawingGeometryResponse,
    OpenAIDrawingSemanticClient,
    OpenAIDrawingSemanticResponse,
    OpenAITwoPassDrawingParser,
    TwoPassDrawingParser,
)
from scope_modeler.extractors.text import (
    DraftMaterial,
    DraftObservation,
    DraftQuestion,
    DraftTask,
    LLMTextExtractor,
    OpenAITextExtractionResponse,
    OpenAITextModelClient,
    TextExtractionDraft,
    TextModelClient,
)
from scope_modeler.extractors.vision import (
    OpenAIVisionModelClient,
    VisionDraftMaterial,
    VisionDraftQuestion,
    VisionDraftTask,
    VisionExtractionDraft,
    VisionExtractor,
    VisionModelClient,
    VisionObservation,
    OpenAIVisionExtractionResponse,
)

__all__ = [
    "BaseExtractor",
    "AudioScopeExtractor",
    "DrawingDimension",
    "DrawingGeometryModelClient",
    "DrawingGeometrySummary",
    "DrawingPoint",
    "DrawingPrimitive",
    "DrawingSemanticModelClient",
    "DrawingSemanticInference",
    "DraftMaterial",
    "DraftObservation",
    "DraftQuestion",
    "DraftTask",
    "ExtractedObservation",
    "ExtractorResult",
    "LLMTextExtractor",
    "MockTranscriber",
    "ObservationValue",
    "OpenAITextExtractionResponse",
    "OpenAITextModelClient",
    "OpenAIDrawingGeometryClient",
    "OpenAIDrawingGeometryResponse",
    "OpenAIDrawingSemanticClient",
    "OpenAIDrawingSemanticResponse",
    "OpenAITwoPassDrawingParser",
    "OpenAIVisionModelClient",
    "TextExtractionDraft",
    "TextModelClient",
    "Transcriber",
    "TranscriptionResult",
    "TranscriptionSegment",
    "TwoPassDrawingParser",
    "VisionDraftMaterial",
    "VisionDraftQuestion",
    "VisionDraftTask",
    "VisionExtractionDraft",
    "VisionExtractor",
    "VisionModelClient",
    "VisionObservation",
    "OpenAIVisionExtractionResponse",
]
